<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!-- Powered by LIMB | http://www.limb-project.com/ -->
<!-- Designed by BIT | http://www.bit-creative.com/ -->

{{include file="_include/cms_vars.phtml" /}}

<html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" lang="en">
  <head>
    {{include file="_include/html_head.phtml" /}}
  </head>
  <body>

    <div id="wrapper">

	  <div id="header">
        <h3>header</h3>
	  </div><!-- #header-->

	  <div id="menu">
        {{include file="_include/menu_plain.phtml" identifier="main_menu" /}}
	  </div><!-- #header-->

	  <div id="content">
        {{slot id="content"}}
	  </div><!-- #content-->

    </div><!-- #wrapper -->

    <div id="footer">
      {{text_block id="footer"/}}
    </div><!-- #footer -->

    {{include file="_include/js_include.phtml" /}}
  </body>
</html>
