{{wrap with="front_layout.phtml"}}

  {{into slot="page_title"}}Восстановление пароля - {{/into}}

  {{into slot="content"}}

    <h1>Восстановление пароля</h1>

    {{form method="POST" id='forgot_password_form' name="forgot_password_form" class="form"}}

      {{include file='_admin_include/form_errors.phtml'/}}

      <p>Введите адрес электронной почты, указанный Вами при регистрации, и мы вышлем вам новый пароль</p>

      {{input type="text" name="email" id="email" title="Email" class='input'/}}

      <input type='submit' id="submit" name='submit' value="Выслать пароль" />

    {{/form}}

  {{/into}}

{{/wrap}}
