{{wrap with="front_layout.phtml"}}

  {{into slot="page_title"}}Новый пароль - {{/into}}

  {{into slot="content"}}

    <h1>Новый пароль</h1>

    {{form method="POST" id='forgot_password_form' name="forgot_password_form"}}

    {{include file='_admin_include/form_errors.phtml'/}}

      <? if($this->show_password_form) { ?>
        
        <dl class="field">
          <dt><label for='password'>Введите пароль</label></dt>
          <dd>{{input type="password" name="password" id="password" title="Пароль" class='input'/}}</dd>
        </dl>

        <dl class="field">
          <dt><label for='password_repeat'>Повторите пароль</label></dt>
          <dd>{{input type="password" name="password_repeat" id="password_repeat" title="Пароль" class='input'/}}</dd>
        </dl>

        <div class="form_buttons">
          <input type='submit' id="submit" name='submit' value="Сменить пароль" />
        </div>

      <? } ?>

    {{/form}}

  {{/into}}

{{/wrap}}
