{{form id='filter_form' name='filter_form' method='post'}}

  <div class='fields'>

    <label for="email">Email:</label>
    {{input type="text" id="email" name="email"/}}
    
    <label for="name">Имя:</label>
    {{input type="text" id="name" name="name"/}}

    <label for="is_banned">Заблокирован?</label>
    {{select id="is_banned" name="is_banned"}}
      {{option value=''}}Все{{/option}}
      {{option value="1"}}Да{{/option}}
      {{option value="0"}}Нет{{/option}}
    {{/select}}

    <label for="is_activated">Активирован?</label>
    {{select id="is_activated" name="is_activated"}}
      {{option value=''}}Все{{/option}}
      {{option value="1"}}Да{{/option}}
      {{option value="0"}}Нет{{/option}}
    {{/select}}

  </div>

  <div class='buttons'>
    {{input type='submit' id='accessory_search_submit' name='search_submit' class="button" value='Фильтр'/}}
    {{input type='submit' id='cancel_filter' name='cancel_filter' class="button" value='Сбросить фильтр'/}}
  </div>

{{/form}}

<div class="clearing"></div>
