lmb_require('limb-cms/core/src/controller/AdminObjectController.class.php');
<? if(count($this->attached_images)) { ?>lmb_require('limb-cms/image/src/helper/UploadImageFileHelper.class.php');<? echo PHP_EOL; } ?>

class Admin{$#model_name}Controller extends AdminObjectController
{
  protected $_object_class_name = '{$#model_name}';

  protected $_default_sort = array('field' => '{$#default_sort_params.field}', 'direction' => '{$#default_sort_params.direction}');

<? if(count($this->attached_images)) { ?>
  protected function _onBeforeValidate()
  {
    parent :: _onBeforeValidate();

<? foreach($this->attached_images as $image_name) { ?>
    UploadImageFileHelper :: validateImageFile(
      $this->item, '{$image_name}',
      $this->request->get('{$image_name}_file_temp'),
      $this->error_list
    );
    <? echo PHP_EOL; ?>
<? } ?>
  }

  protected function _onAfterSave()
  {
    parent :: _onAfterSave();

<? foreach($this->attached_images as $image_name) { ?>
    UploadImageFileHelper :: attachOrDeleteImageFile(
      $this->item, '{$image_name}',
      $this->request->get('{$image_name}_file_temp'),
      (bool)$this->request->get('{$image_name}_file_delete')
    );
    <? echo PHP_EOL; ?>
<? } ?>
  }
<? } ?>

}