<meta http-equiv='Content-Type' content='text/html; charset=utf-8' />

<title>{{slot id='page_title'/}}</title>
<meta name="keywords" content='{{slot id="page_keywords" /}}'/>
<meta name="description" content='{{slot id="page_description" /}}'/>

<link rel="stylesheet" type="text/css" href="/styles/main.css?{$#static_files_version}" />
<!--[if lt IE 8]><link rel="stylesheet" type="text/css" href="/styles/main_ie.css?{$#static_files_version}" /><![endif]-->
<!--[if lt IE 7]><link rel="stylesheet" type="text/css" href="/styles/main_ie6.css?{$#static_files_version}" /><![endif]-->

<link rel="icon" href="/favicon.ico?{$#static_files_version}" type="image/x-icon" />

{{slot id='html_head' /}}
