<? 
  lmb_require('src/finder/MenuFinder.class.php');
  lmb_require('src/model/Menu.class.php');
  
  if(!isset($identifier)) $identifier = Menu::findRoot()->get('identifier');
  $node = MenuFinder :: findOneByIdentifier($identifier);
  $iterator = MenuFinder :: findChildrenArrayForFront($node);
?>

{{list using="{$iterator}" as="{$item}" }}
  <ul>
    {{list:item}}
      <li>
        <a href="{$item.url}">{$item.title}</a>
      </li>
    {{/list:item}}
  </ul>
{{/list}}
