<? 
  lmb_require('src/finder/MenuFinder.class.php');
  
  if(!isset($identifier)) $identifier = Menu::findRoot()->get('identifier');
  $node = MenuFinder :: findOneByIdentifier($identifier);
  $iterator = MenuFinder :: findChildrenTree($node);
?>

{{tree using="{$iterator}" as="{$item}" kids_prop="preloaded_children" counter="$counter"}}
  <ul>
    {{tree:node}}
      <li>
        <a href="{$item.url}">{$item.title}</a>
        {{tree:nextlevel /}}
      </li>
    {{/tree:node}}
  </ul>
{{/tree}}
