{{template name="object_action"}}
  <?
    $controller = isset($controller) ? $controller : lmbToolkit::instance()->getDispatchedController()->getName();
    $item = isset($item) ? $item : false;
    $is_link = isset($is_link) ? $is_link : false;
    $icon = isset($icon) ? $icon : "add";
    $i18n = isset( $i18n)? $i18n: 1;
    if( $i18n)
      $title = lmb_i18n( $title, "cms");
  ?>
  <a href='{{route_url params="controller:{$controller},action:{$action},id:{$item.id}"/}}' title="{$title}" class="thickbox">
    <img src='/shared/cms/images/icons/{$icon|default:"add"}.png'/>
    <? if($is_link) echo $title; ?>
  </a>
{{/template}}

{{template name="object_action_edit"}}
  <?
    $controller = isset($controller) ? $controller : lmbToolkit::instance()->getDispatchedController()->getName();
    $is_link = isset($is_link) ? $is_link : false;
    $title = isset($title) ? $title : lmb_i18n('Edit', 'cms');
    $icon = isset($icon) ? $icon : "pencil";
  ?>
  <a href='{{route_url params="controller:{$controller},action:edit,id:{$item.id}"/}}' title="{$title}" class="thickbox">
    <img src='/shared/cms/images/icons/{$icon|default:"pencil"}.png'/>
    <? if($is_link) echo $title; ?>
  </a>
{{/template}}

{{template name="object_action_delete"}}
  <?
    $controller = isset($controller) ? $controller : lmbToolkit::instance()->getDispatchedController()->getName();
    $is_link = isset($is_link) ? $is_link : false;
    $title = isset($title) ? $title : lmb_i18n('Delete', 'cms');
    $icon = isset($icon) ? $icon : "delete";
  ?>
  
  <a href='#' onclick="if(confirm('{{i18n text='Are you sure want to delete selected objects?' domain='cms'/}}')) {jQuery.post('{{route_url params='controller:{$controller},action:delete'/}}', {ids:{$item.id}}, function(){document.location.reload()})}"  title="{$title}">
    <img src='/shared/cms/images/icons/{$icon|default:"delete"}.png'/>
    <? if($is_link) echo $title; ?>
  </a>
{{/template}}

{{template name="object_action_publish"}}
  <?
    $controller = isset($controller) ? $controller : lmbToolkit::instance()->getDispatchedController()->getName();
    $is_link = isset($is_link) ? $is_link : false;
    $title = isset($title) ? $title : lmb_i18n('Publish', 'cms');
    $icon = isset($icon) ? $icon : "lightbulb";
  ?>
  <a href='{{route_url params="controller:{$controller},action:publish,id:{$item.id}"/}}' title="{$title|default:'Показать'}" class="publish thickbox">
    <img src='/shared/cms/images/icons/{$icon|default:"lightbulb"}.png'/>
    <? if($is_link) echo $title; ?>
  </a>
{{/template}}

{{template name="object_action_unpublish"}}
  <?
    $controller = isset($controller) ? $controller : lmbToolkit::instance()->getDispatchedController()->getName();
    $is_link = isset($is_link) ? $is_link : false;
    $title = isset($title) ? $title : lmb_i18n('Unpublish', 'cms');
    $icon = isset($icon) ? $icon : "lightbulb_off";
  ?>

  <a href='{{route_url params="controller:{$controller},action:unpublish,id:{$item.id}"/}}' title="{$title|default:'Скрыть'}" class="unpublish thickbox">
    <img src='/shared/cms/images/icons/{$icon|default:"lightbulb_off"}.png'/>
    <? if($is_link) echo $title; ?>
  </a>
{{/template}}

{{template name="object_action_revert_publish"}}
  <? 
    $controller = isset($controller) ? $controller : lmbToolkit::instance()->getDispatchedController()->getName();
    if($item->getIsPublished()){
  ?>
    {{apply template="object_action_unpublish" item="{$item}" icon="lightbulb_off" controller="{$controller}"/}}
  <? }else{ ?>
    {{apply template="object_action_publish" item="{$item}" icon="lightbulb" controller="{$controller}"/}}
  <? } ?>
{{/template}}

{{template name="publish_status"}}
  <? echo $item->getIsPublished() ? '<img src="/shared/cms/images/icons/lightbulb.png" title="Опубликована"/>' : '<img src="/shared/cms/images/icons/lightbulb_off.png" title="Скрыта"/>'; ?>
{{/template}}
