{{template name="object_priority_input"}}
  {{input type='text' 
          class='priority'
          name='priority_items[{$item.id}]'
          id='priority_items[{$item.id}]'
          value='{$item.priority}'
          title='Priority'
          size='3'
  /}}
{{/template}}

{{template name="save_priority_button"}}
  <?
    $controller = isset($controller) ? $controller : lmbToolkit::instance()->getDispatchedController()->getName();
    $action = isset($action) ? $action : 'priority';
    $params = isset($params)? $params : '';
    
    $url = lmbToolkit :: instance()->getRoutesUrl( array('controller' => $controller, 'action' => $action));
    $url .= '?' . $params;
    
    $title = isset($title) ? $title : lmb_i18n('Change order', 'cms');
  ?>
  <input type="button" class='button' value='{$title}' onclick='openWindowForSavePriority("{$title}?", "{$url}", this);return false;'/>
{{/template}}

{{into slot="js"}}
  function openWindowForSavePriority(title, url, obj)
  {
    var params = '&';
    jQuery(obj).parent().parent().parent().find('.priority').each(function(){params += this.name + '=' + this.value + '&';});
    tb_show(title, url + params + 'TB_iframe=true&width=640&height=480');
  }
{{/into}}