{{wrap with="admin_modal_page_layout.phtml" into="content_zone"}}


  <h1>Проверка настроек почты на сервере</h1>

  {{form id='test_email' name='test_email' method='post' enctype="multipart/form-data"}}
    {{include file='_admin/form_errors.phtml'/}}

    <div class='tabs'>

      <ul>
        <li id='send_email'><a>Отсылка письма</a></li>
        <li id='config_email'><a>Настроки отсылки почты</a></li>
      </ul>

      <div id="tab_send_email">
        <dl class='field'>
          <dt>{{label for="subject"}}Заголовок:{{/label}}</dt>
          <dd>{{input id="subject" name="subject" type="text" title="Заголовок"/}}</dd>
        </dl>

        <dl class='field'>
          <dt>{{label for="sender"}}Адрес отправителя:{{/label}}</dt>
          <dd>{{input id="sender" name="sender" type="text" title="Адрес отправителя"/}}</dd>
        </dl>

        <dl class='field'>
          <dt>{{label for="recipient"}}Адрес получателя:{{/label}}</dt>
          <dd>{{input id="recipient" name="recipient" type="text" title="Адрес получателя"/}}</dd>
        </dl>

        {{label for="content"}}Текст письма:{{/label}}
        {{wysiwyg id="content" name="content" width="100%" height="150px" title="Текст письма"/}}

      </div>
    </div>
    <div id="tab_config_email">

      {{list using='{$#mail_config}' as="$v" key="$k" counter='$counter_product'}}
        <div class='list'>
          <table>
            <tr>
              <th width="50%"></th>
              <th width="50%"></th>
            </tr>
          {{list:item}}
            <tr>
              <td>{$k}</td>
              <td>{$v}</td>
            </tr>
          {{/list:item}}
          {{list:empty}}
            <tr colspan="2">Нет Настроек</tr>
          {{/list:empty}}
          </table>
        </div>
      {{/list}}
    </div>

    {{include file='_admin/form_buttons.phtml' save_button_name="Отправить" is_used_ajax="0"/}}
  {{/form}}

{{/wrap}}
