{{wrap with="admin_modal_page_layout.phtml" into="content_zone"}}

  {{form id='view_file' name='view_file' method='post' enctype="multipart/form-data"}}
    <a href="javascript: void(0);" onclick="$('#path').val($('#current_path').val()+'<?php echo DIRECTORY_SEPARATOR;?>..');$('#view_file').submit();">
      <img src='/shared/cms/images/icons/arrow_up.png'/>
    </a>
    &nbsp;
    <a href="javascript: void(0);" onclick="$('#path').val($('#current_path').val());$('#view_file').submit();">
      <img src='/shared/cms/images/icons/arrow_refresh_small.png'/>
    </a>

    {{include file='_admin/form_errors.phtml'/}}
    {{input id="current_path" name="current_path" type="hidden" value="$#current_path"/}}
    {{input id="path" name="path" type="hidden" title="path" value=""/}}
  {{/form}}

  <? if($this->type == 'file' || $this->type == 'text'){?>
    <textarea class="php" name="code">
    {$#content|raw}
    </textarea>

  <?}elseif($this->type == 'image'){?>
    <img src="{$#content}">

  <?}elseif($this->type == 'flash'){?>
    <embed
      type="application/x-shockwave-flash"
      pluginspage="http://www.macromedia.com/go/getflashplayer"
      src="{$#content}"
      width="685"
      height="250"
      play="true"
      loop="true"
      menu="true"
    >
    </embed>

  <?}elseif($this->type == 'dir'){?>
    {{list using="{$#content}"}}
      <table width="100%">
        <tr>
          <th>Name</th>
          <th>Size</th>
          <th>Type</th>
        </tr>
      {{list:item}}
        <tr>
          <td><a href="javascript:void(0)" onclick="$('#path').val($('#current_path').val()+'<?php echo DIRECTORY_SEPARATOR;?>{$item.name}');$('#view_file').submit();">{$item.name}</a></td>
          <td>{$item.size}</td>
          <td>{$item.type}</td>          
        </tr>
      {{/list:item}}
      </table>
    {{/list}}

  <?}?>

{{/wrap}}

{{into slot="css_zone"}}
  #header h1 {margin:15px 0 0;}
  
  #body code {font-size:1.3em;background:#F0F0F0;}
  #body p {margin:15px 0 0;}
  #body textarea {width:100%;height:150px;}
  #body ul, #body ol {margin:0 0 10px 10px;padding:0 20px;}
{{/into}}

{{into slot="header_zone"}}
  <link rel="stylesheet" href="/shared/cms/syntax_hightlighter/SyntaxHighlighter.css?{$#static_files_version}" type="text/css"> 
{{/into}}

{{into slot="js_include"}}
  <script language="javascript" src="/shared/cms/syntax_hightlighter/shCore.js?{$#static_files_version}"></script>
  <script language="javascript" src="/shared/cms/syntax_hightlighter/shBrushPhp.js?{$#static_files_version}"></script>
  <script language="javascript" src="/shared/cms/syntax_hightlighter/shBrushSql.js?{$#static_files_version}"></script>
  <script language="javascript" src="/shared/cms/syntax_hightlighter/shBrushXml.js?{$#static_files_version}"></script>
{{/into}}

{{into slot="js_ready"}}
  if(navigator.userAgent.indexOf('Opera 7') == -1 && dp)
    dp.SyntaxHighlighter.HighlightAll('code', true, true, false);
{{/into}}
