{{wrap with="admin_page_layout.phtml"}}

  {{into slot="content_zone"}}

    {{include file="_admin_object_tpls/actions_tpls.phtml"/}}
    {{include file='_admin/tree_breadcrumbs.phtml' item="{$#item}" base_path="/admin_menu/display/" link_field='id' root_path='/admin_menu/' root_title="Список Меню" /}}
    
    <div id="header">
      <h1>Меню</h1>

      <div class="header_actions">
        <? if(!$this->item->isRoot()) : ?>
          {{apply template="object_action" item="{$#item}" action="create" is_link="true" title="Добавить меню" icon="page_add"/}}
          {{apply template="object_action_edit" item="{$#item}" icon="page_edit" is_link="true" title="Редактировать"/}}
          {{apply template="object_action_revert_publish" item="{$#item}"/}}
          {{apply template="object_action_delete" item="{$#item}" is_link="true"/}}
        <?  else:  ?>
          {{apply template="object_action" item="{$#item}" action="create" title="Создать меню" icon="page_add" is_link="true"/}}
        <? endif ?>
      </div>

      {{include file='_admin/pager.phtml' items='{$#items}'/}}
    </div>

    <div id="body">
      {{include file='admin_menu/include/items_list.phtml' iterator="{$#items}"/}}
    </div>

  {{/into}}

{{/wrap}}
