{{wrap with="admin_page_layout.phtml" in="content_zone"}}
  <? $controller = $this->toolkit->getDispatchedController()->getName(); ?>

  {{into slot="content_zone"}}
  
    <div id="header">
      <h1>Документация Limb Cms</h1>
      <br/>
    </div>
      
    <div id="body">
      {$#content|raw}
    </div>
    
  {{/into}}
  
  {{into slot="css_zone"}}
    #header h1 {margin:15px 0 0;}
    
    #body code {font-size:1.3em;background:#F0F0F0;}
    #body p {margin:2px 0 0;}
    #body textarea {width:100%;height:150px;}
    #body ul, #body ol {margin:0 0 10px 10px;padding:0 20px;}
  {{/into}}
  
  {{into slot="header_zone"}}
    <link rel="stylesheet" href="/shared/cms/syntax_hightlighter/SyntaxHighlighter.css?{$#static_files_version}" type="text/css"> 
  {{/into}}
  
  {{into slot="js_include"}}
    <script language="javascript" src="/shared/cms/syntax_hightlighter/shCore.js?{$#static_files_version}"></script>
    <script language="javascript" src="/shared/cms/syntax_hightlighter/shBrushPhp.js?{$#static_files_version}"></script>
    <script language="javascript" src="/shared/cms/syntax_hightlighter/shBrushSql.js?{$#static_files_version}"></script>
    <script language="javascript" src="/shared/cms/syntax_hightlighter/shBrushXml.js?{$#static_files_version}"></script>
  {{/into}}
  
  {{into slot="js_ready"}}
    if(navigator.userAgent.indexOf('Opera 7') == -1 && dp)
      dp.SyntaxHighlighter.HighlightAll('code', true, true, false);
  {{/into}}
{{/wrap}}
