<?php
  $tree_field_name = isset( $tree_field_name)? $tree_field_name: 'parent_id';
  $object_class_name = isset($object_class_name)? $object_class_name: lmbToolkit::instance()->getObjectClassName();
 
  $parent_id = isset( $this->item)? $this->item->get( $tree_field_name): 0;
  $criteria = !isset( $not_tree_edit) && isset( $this->item) && !$this->item->isDirty()? "NOT path LIKE '{$this->item->path}%'": "1=1";

  $options = array();
  $tree = lmbActiveRecord::find( $object_class_name, array( 'criteria' => $criteria, 'sort' => array( 'path' => 'ASC')));

  foreach( $tree as $item)
  {
    $tab = str_repeat( " - ", $item->level);
    
    if( $item->isRoot())
    {
      $root_title = lmb_i18n( 'Root element', 'cms');
      $options[$item->id] = $tab . $root_title;
    }
    else
      $options[$item->id] = $tab . $item->title;
    
  }

  $selected_value = array( $parent_id);
  $selected_value_object = new lmbObject( array('value' => $parent_id));
?>

{{select id="{$name}" options="$options" value="$selected_value_object" value_field="value" /}}
