{{wrap with="front_layout.phtml"}}

  {{into slot="page_title"}}Смена пароля - {{/into}}

  {{into slot="content"}}
  
    <div class="breadcrumbs">
      <a href="/user_home">Личный кабинет</a> &raquo;
      <b>Смена пароля</b>
    </div>
  
    <h1>Смена пароля</h1>

    {{form method="POST" id='forgot_password_form' name="forgot_password_form"}}

      {{include file='_admin/form_errors.phtml'/}}

      <dl class="field">
        <dt><label for='password'>Текущий пароль</label></dt>
        <dd>{{input type="password" name="old_password" id="old_password" title="Текущий пароль" class='input'/}}</dd>
      </dl>

      <dl class="field">
        <dt><label for='password'>Новый пароль</label></dt>
        <dd>{{input type="password" name="password" id="password" title="Новый пароль" class='input'/}}</dd>
      </dl>

      <dl class="field">
        <dt><label for='password_repeat'>Повторите пароль</label></dt>
        <dd>{{input type="password" name="password_repeat" id="password_repeat" title="Пароль" class='input'/}}</dd>
      </dl>

      <div class="form_buttons">
        <input type='submit' id="submit" name='submit' value="Сменить пароль" />
      </div>

    {{/form}}

  {{/into}}

{{/wrap}}
