{{list using="{$iterator}" as="$item" counter="$counter" parity='$my_parity'}}

  {{include file="_admin_object_tpls/selectors_tpls.phtml"/}}
  {{include file="_admin_object_tpls/actions_tpls.phtml"/}}
  {{include file="_admin_object_tpls/priority_tpls.phtml"/}}
  
  <div class='list' id="items">
    <div class='list_actions'>
      {{apply template="selectors_button" action="delete" title="Удалить"/}}
      {{apply template="save_priority_button" params="parent_id={$#item.id}"/}}
    </div>
    <table>
      <tr>
        <th></th>
        <th>#ID</th>
        <th>Приоритет</th>
        <th>Артикул</th>
        <th width="80%">Заголовок</th>
        <th>Цена</th>
        <th>Дата<br/>создания</th>
        <th>Последнее<br/>обновление</th>
        <th>{{i18n text="Actions" domain="cms"/}}</th>
      </tr>
      {{list:item}}
        <tr class="{$my_parity}">
          <td>{{apply template="selector" value="{$item.id}"/}}</td>
          <td>{$item.id}</td>
          <td>{{apply template="object_priority_input" item="{$item}" add_sort_prefix="{$#add_sort_prefix}" /}}</td>
          <td>{$item.article}</td>
          <td>{$item.title}</td>
          <td>{$item.price}</td>
          <td>{$item.ctime|i18n_date:"", "stamp", "short_date_time"}</td>
          <td>{$item.utime|i18n_date:"", "stamp", "short_date_time"}</td>
          <td class='actions'>
            {{apply template="object_action_revert_publish" controller="admin_catalog_product" item="{$item}" /}}
            {{apply template="object_action_edit" controller="admin_catalog_product" icon="cart_edit" item="{$item}" /}}
            {{apply template="object_action_delete" controller="admin_catalog_product" icon="cart_delete" item="{$item}" /}}
          </td>
        </tr>
      {{/list:item}}
      {{list:empty}}
        <div class="empty_list">Товары не найдены</div>
      {{/list:empty}}
    </table>
    <div class='list_actions'>
      {{apply template="selectors_button" action="delete" title="Удалить"/}}
      {{apply template="save_priority_button" params="parent_id={$#item.id}"/}}
    </div>
  </div>

{{/list}}
