{{list using='{$iterator}' parity='{$parity}'}}

  {{include file="_admin_object_tpls/selectors_tpls.phtml"/}}
  {{include file="_admin_object_tpls/actions_tpls.phtml"/}}
  {{include file="_admin_object_tpls/priority_tpls.phtml"/}}

  <div class="list">
    <div class='list_actions'>
      {{apply template="selectors_button" action="delete" title="Удалить"/}}
      {{apply template="save_priority_button" params="parent_id={$#item.id}"/}}
    </div>
    
    <table>
      <tr>
        <th>{{apply template="selectors_toggler"/}}</th>
        <th>#ID </th>
        <th>Порядок </th>
        <th>Идентификатор </th>
        <th width="80%">Название </th>
        <th>Статус</th>
        <th>Дата<br/>создания</th>
        <th>Последнее<br/>обновление</th>
        <th>&nbsp;</th>
      </tr>
      {{list:item}}
        <tr class='{$parity}'>
          <td>
            <?php if(!$item->isReadOnly()) { ?>
              {{apply template="selector" value="{$item.id}"/}}
            <? }?>
          </td>
          <td>#{$item.id}</td>
          <td>{{apply template="object_priority_input" item="$item"/}}</td>
          <td>{$item.identifier}</td>
          <td>
            <a href='{{route_url params="action:display,id:{$item.id}"/}}' title="Перейти к вложенным пунктам" style="font-weight:bold;">{$item.title}</a>
            <span title="Вложенных пунктов: ({$item.kids->count()})">({$item.kids->count()})</span>
            <? if($item->url) { ?>
              <br/>[&nbsp;<a href="{$item.url}" title="Куда ссылаеться пункт меню?" target="_blank">{$item.url}</a>&nbsp;]
            <? } ?>
          </td>
          <td><? echo $item->getIsPublished() ? '<img src="/shared/cms/images/icons/lightbulb.png" title="Опубликована"/>' : '<img src="/shared/cms/images/icons/lightbulb_off.png" title="Скрыта"/>'; ?></td>
          <td>{$item.ctime|i18n_date:"", "stamp", "short_date_time"}</td>
          <td>{$item.utime|i18n_date:"", "stamp", "short_date_time"}</td>
          <td class='actions'>
          <? if($item->getIsPublished()): ?>
            {{apply template="object_action_unpublish" item="{$item}" icon="lightbulb_off"/}}
          <?  else:  ?>
            {{apply template="object_action_publish" item="{$item}" icon="lightbulb"/}}
          <? endif; ?>
          {{apply template="object_action_edit" item="{$item}" icon="page_edit"/}}
          {{apply template="object_action_delete" item="{$item}"/}}
          </td>
        </tr>
      {{/list:item}}
      
      {{list:empty}}
        <div class="empty_list">Пункты меню не найдены</div>
      {{/list:empty}}
    </table>
    
    <div class='list_actions'>
      {{apply template="selectors_button" action="delete" title="Удалить" /}}
      {{apply template="save_priority_button" controller="admin_document" action="priority" params="parent_id={$#item.id}"/}}
    </div>
  </div>
{{/list}}
