{{wrap with="admin_modal_page_layout.phtml" into="content_zone"}}
  {{include file='_admin_object_tpls/fieds_tpls.phtml'/}}

  {{form id='user_form' name='user_form' method='post'}}

    <?php $this->editing_user= lmbActiveRecord::findById('lmbCmsUser',$this->request->get('id'));?>
    <h1>{{i18n text="Change administrator password" domain="cms"/}}: {$#editing_user.login} - {$#editing_user.name}</h1>

    {{include file='_admin/form_errors.phtml'/}}

    <div class='tabs'>

      <ul class="bookmarks">
        <li id='properties_link'><a href="#">{{i18n text="Properties" domain="cms"/}}</a></li>
      </ul>

      <div id="tab_properties" class='bookmarks_content'>
        {{apply template="password_field" name="password" title="Current password" required="1" value=""/}}
        {{apply template="password_field" name="new_password" title="New password" required="1"/}}
        {{apply template="password_field" name="repeat_new_password" title="Repeat new password" required="1"/}}
      </div>

    </div>

    {{include file='_admin/form_buttons.phtml'/}}

  {{/form}}

{{/wrap}}
