{{include file='_admin_object_tpls/fieds_tpls.phtml'/}}
{{include file='_admin/form_errors.phtml'/}}

<div class='tabs'>

  <ul>
    <li id='properties'><a href="#">{{i18n text="Properties" domain="cms"/}}</a></li>
  </ul>

  <div id="tab_properties">
    {{apply template="text_field" name="url" title="URL" required="1"/}}
    {{apply template="text_field" name="title" title="Title" required="1"/}}
    {{apply template="textarea_field" name="keywords" title="Keywords"/}}
    {{apply template="textarea_field" name="description" title="Description"/}}
  </div>

</div>

{{include file='_admin/form_buttons.phtml'/}}
