[[wrap with="admin_page_layout.phtml" in="content_zone"]]

  [[include file="_admin_object_tpls/selectors_tpls.phtml"/]]
  [[include file="_admin_object_tpls/actions_tpls.phtml"/]]
  [[include file="_admin_object_tpls/priority_tpls.phtml"/]]

  <div id="header">
    <h1>{$#model_name}</h1>
    <div class="header_actions">
      [[apply template="object_action" action="create" title="Создать {$#model_name}" is_link="true"/]]
    </div>

    [[include file='_admin/pager.phtml' items='[$#items]'/]]
  </div>

  <div id="body">

    [[list using="[$#items]" as="$item" counter="$counter" parity='$parity']]

      <div class='list'>
        <div class='list_actions'>
          {{if var="$this->published_exist"}}
            [[apply template="selectors_button" action="revert_publish" title="Опубликовать / Скрыть"/]]
          {{/if}}
          {{if var="$this->priority_exist"}}
            [[apply template="save_priority_button" /]]
          {{/if}}
          [[apply template="selectors_button" action="delete" title="Удалить" /]]
        </div>
        <table>
          <tr>
            <th>[[apply template="selectors_toggler"/]]</th>{{list using="{$#columns}" as="$column"}}{{list:item}}
            <th>{$column->getName()}</th>{{/list:item}}
            <th>&nbsp;</th>
          {{/list}}</tr>

          [[list:item]]
            <tr class="[$parity]">
              <td>[[apply template="selectors_toggler" value="[$item.id]"/]]</td>{{list using="{$#columns}" as="$column"}}{{list:item}}
              <td><? $column_name = $column->getName(); ?>{$#fields_for_display[$column_name]|raw}</td>{{/list:item}}{{/list}}
              <td class='actions'>
                {{if var="$this->published_exist"}}[[apply template="object_action_revert_publish" item="[$item]" /]]{{/if}}
                [[apply template="object_action_edit" item="[$item]"/]]
                [[apply template="object_action_delete" item="[$item]"/]]
                &nbsp;
                {{list using="{$#attached_images}" as="$image_name"}}{{list:item}}{{-
                  }}[[apply template="object_action_image" item='[$item]' object_name='{$image_name}' title='{$image_name}' /]]{{-
                }}{{/list:item}}{{/list}}
              </td>
            </tr>
          [[/list:item]]
          [[list:empty]]
            <div class="empty_list">{$#model_name} не найдены</div>
          [[/list:empty]]
        </table>
        <div class='list_actions'>
          {{if var="$this->published_exist"}}
            [[apply template="selectors_button" action="revert_publish" title="Опубликовать / Скрыть"/]]
          {{/if}}
          {{if var="$this->priority_exist"}}
            [[apply template="save_priority_button" /]]
          {{/if}}
          [[apply template="selectors_button" action="delete" title="Удалить" /]]
        </div>
      </div>

    [[/list]]

  </div>

[[/wrap]]
