{{include file='_admin_object_tpls/fieds_tpls.phtml'/}}

{{apply template="text_field" name="login" title="Login" required="1"/}}
{{apply template="text_field" name="name" title="Name" required="1"/}}
{{apply template="text_field" name="email" title="E-mail" required="1"/}}

<dl class='field'>
  <dt>{{label for="role_id" errorclass='error_label'}}{{i18n text="Group" domain="cms"/}}:{{/label}}</dt>
  <dd>
    <?php $list = lmbCmsUser::getRoleTypeList(); ?>
    {{select id='role_type' name='role_type' options="{$list}" /}}
  </dd>
</dl>
