{{include file='_admin_object_tpls/fieds_tpls.phtml'/}}

<div class='tabs'>

  <ul>
    <li id='properties'><a href="#">{{i18n text="Properties" domain="cms"/}}</a></li>
  </ul>

  <div id="tab_properties" class='bookmarks_content'>

    <div class="left_side">
      {{include file='admin_user/include/common_fields.phtml'/}}
    </div>

    <div class="right_side">
      {{apply template="password_field" name="password" title="Password" required="1"/}}
      {{apply template="password_field" name="repeat_password" title="Repeat password" required="1"/}}
    </div>

  </div>

</div>
