<meta http-equiv='Content-Type' content='text/html; charset=utf-8' />

<?php lmb_require('limb-cms/core/src/model/lmbCmsSeo.class.php'); ?>
<title><?php echo lmbCmsSeo :: getMetaTitle(); ?></title>
<meta name="description" content="<?php echo  lmbCmsSeo :: getMetaDescription(); ?>"/>
<meta name="keywords" content="<?php echo lmbCmsSeo :: getMetaKeywords(); ?>"/>

<link rel="stylesheet" type="text/css" href="/styles/main.css?{$#static_files_version}" />
<!--[if lt IE 8]><link rel="stylesheet" type="text/css" href="/styles/main_ie.css?{$#static_files_version}" /><![endif]-->
<!--[if lt IE 7]><link rel="stylesheet" type="text/css" href="/styles/main_ie6.css?{$#static_files_version}" /><![endif]-->

<link rel="icon" href="/favicon.ico?{$#static_files_version}" type="image/x-icon" />

{{slot id='html_head' /}}
