{{wrap with="front_layout.phtml"}}

  {{into slot="description"}}{$#item.description}{{/into}}
  {{into slot="keywords"}}{$#item.keywords}{{/into}}
  {{into slot="title"}}{$#item.title}{{/into}}

  {{into slot="content"}}
    <? $list = array(array('url' => '/', )); ?>
    {{include file='_include/breadcrumbs.phtml' tree_node="{$#item}" list="{$list}" link_field='uri'/}}

    <h1>{$#item.title}</h1>

    {$#item.content|raw}
  {{/into}}

{{/wrap}}
